services:
  tenant-{{TENANT_ID}}-app:
    build: .
    container_name: tenant-{{TENANT_ID}}-app
    restart: unless-stopped
    ports:
      - "{{APP_PORT}}:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY={{SECRET_KEY}}
      - TENANT_ID={{TENANT_ID}}
      - TENANT_PLAN={{TENANT_PLAN}}
      - TENANT_EMAIL={{TENANT_EMAIL}}
      - TENANT_COLOR={{TENANT_COLOR}}
      - DATABASE_PATH=/app/data/courses.db
      - API_BASE_URL={{API_BASE_URL}}
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true