services:
  tenant-test-academy-app:
    build: .
    container_name: tenant-test-academy-app
    restart: unless-stopped
    ports:
      - "5102:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=ff4ef9defc6ae85698dca6fd26381ca31c184be43fa7cd646c423b36a2c4bc6f
      - TENANT_ID=test-academy
      - TENANT_PLAN=basis
      - TENANT_EMAIL=test@example.com
      - TENANT_COLOR=ocean-blue
      - DATABASE_PATH=/app/data/courses.db
      - API_BASE_URL=https://api.kurs24.io
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true