version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
      - "2019:2019"   # Admin API (internal only)
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./caddy/dynamic_subdomains:/etc/caddy/dynamic_subdomains
    networks:
      - caddy-network
      - backend-network

networks:
  caddy-network:
    name: caddy-network
  backend-network:
    external: true